In [32]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [49]:
b = np.random.randn(5,5)

In [51]:
b

array([[ 1.47269581, -0.26229075, -0.26971812,  1.97957923,  0.27838674],
       [ 0.50465718,  0.00460243, -0.92905394,  1.39172488,  0.02235737],
       [-0.62587264,  0.85808359, -0.49007902, -0.54793763, -0.8935685 ],
       [ 0.81066735,  0.58440006, -0.67271049,  1.49264845, -1.32399498],
       [-0.37282699, -0.18941158,  1.55241594, -0.18478521, -0.98208692]])

In [52]:
def swap_row(row_num1,row_num2,array):
    #source: https://stackoverflow.com/questions/54069863/swap-two-rows-in-a-numpy-array-in-python/54069951
    array[[row_num1-1, row_num2-1]] = array[[row_num2-1, row_num1-1]] #swapping the row by given row_num-1
    return array
print(swap_row(1,2,b))

[[ 0.50465718  0.00460243 -0.92905394  1.39172488  0.02235737]
 [ 1.47269581 -0.26229075 -0.26971812  1.97957923  0.27838674]
 [-0.62587264  0.85808359 -0.49007902 -0.54793763 -0.8935685 ]
 [ 0.81066735  0.58440006 -0.67271049  1.49264845 -1.32399498]
 [-0.37282699 -0.18941158  1.55241594 -0.18478521 -0.98208692]]


**75. How to compute averages using a sliding window over an array?**

In [31]:
#enter the window size in tuple form e.g: (2,3) but any dim should not be greater than any dim of original array
d = np.random.randn(1,10)
def moving_avg_pool(window_size,array,strides):
    if (window_size[0] > array.shape[0] or window_size[0] > array.shape[1]) or (window_size[1] > array.shape[0] or window_size[1] > array.shape[1]):
        print('===> Window size can not be greater than the array itself!')
        return np.nan
    else:    
        r = (array.shape[0]-window_size[0]+1)//strides
        c = (array.shape[1]-window_size[1]+1)//strides
        avg_array = np.zeros((r,c))
        for k,i  in enumerate(range(0,r)):
            for l,j in enumerate(range(0,c)):
                #taking average of  window size array from the main array
                if l>0:
                    avg_array[k,l] = avg_array[k,l-1] + np.sum(array[i:i+window_size[0], j:j+window_size[1]])/ ((window_size[0] * window_size[1])+1)
                else:
                    avg_array[k,l] = np.sum(array[i:i+window_size[0], j:j+window_size[1]])/ (window_size[0] * window_size[1])
        return avg_array
print('The moving average of the given is:\n','='*34,'\n',moving_avg_pool((1,1),d,1))            

The moving average of the given is:
 [[-0.53242828 -0.6148043  -1.02471243 -0.4427385  -0.67368252 -0.7588214
  -1.75934372 -1.65264758 -1.59806644 -1.46678455]]
